version: "3.4"

services:
  database:
    container_name: time-punch-postgres
    image: "postgres:14-alpine"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    hostname: postgres
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  time-punch-api:
    container_name: time-punch-api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - .:/usr/app
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - DATABASE_HOST=database
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - RUN_ON=${RUN_ON}
      - SESSION_SECRET=${SESSION_SECRET}
      - GOOGLE_AUTH_CLIENT_ID=${GOOGLE_AUTH_CLIENT_ID}
      - GOOGLE_AUTH_CLIENT_SECRET=${GOOGLE_AUTH_CLIENT_SECRET}
      - GOOGLE_AUTH_CLIENT_SCOPE=${GOOGLE_AUTH_CLIENT_SCOPE}
      - LOGIN_REDIRECT_URL=${LOGIN_REDIRECT_URL}
    depends_on:
      database:
        condition: service_healthy
